server:
  port: 9900
spring:
  application:
    name: geekcloud-test
  cache:
    type: redis

geekcloud:
  log:
    enabled: true
    type: db
logging:
  file:
    path: /data/projects/logs
    name: ${logging.file.path}/${spring.application.name}/root.log
  level:
    com.github.geekcloud: debug
